### ISSUE TITLE
Add support for case classes with multiple constructors

### ISSUE THREAD

**Issue by codahale** [codahale/jerkson#28]
As per #27, I need to look into matching the parsed `@ScalaSignature` symbols up with the class's constructors.

**Comment by manuelbernhardt** [comment]
Knowing nothing about @ScalaSignature I got caught up in reading more about it, and in regards to constructors I came across http://stackoverflow.com/questions/6282464 which seems to match against `MethodSymbol(SymbolInfo("<init>", owner, _, _, _, _), _)` in order to fetch case class constructors.

Not sure if it can help but I thought it'd be worth mentioning anyway.

**Comment by codahale** [comment]
There's a blocker here with supporting both multiple constructors _and_ `Option` parameters.

For example, consider the following case class:

``` scala
case class Person(id: Long, name: String, email: Option[String]) {
  def this(id: Long, name: String) = this(id, name, Some("default@example.com"))
}
```

How would one then deserialize the following JSON object?

``` javascript
{"id": 1, "name": "Coda"}
```

If we prioritize the case accessor, we would produce `Person(1, "Coda", None)`.

If we prioritize the constructor with the best-matching parameters, we would produce `Person(1, "Coda", Some("default@example.com"))`.

I can see rationales for both of these approaches, which means end-users will be surprised by either.

So I think the way I'll settle this is by just not throwing an exception for case classes with multiple constructors but also not considering those constructors for deserialization targets.
